Implementing the ImageBlender class
Xrayez/godot-imagetools pull request #5
Opened 2020-05-30 15:21 UTC by 98teg

Yesterday I talked with you about wanting to implement some kind of custom image blending. Here is the solution I came up with. It is a new class that has a method which applies the blend. The class is called ImageBlender because it stores all the information about the blend operation. I follow the specification of OpenGL blending methods. I want to also implement some kind of method which admits a mask parametter in the future.

2020-05-30 16:47 UTC, Xrayez commented
This is nice, thanks for taking the time to make this!

Upon initial thinking, I thought about making this directly available as `ImageTools.blend_rect()`, but given that there's already quite of properties which can be configured, yeah I think this justifies making an entire class for it (not to mention that with the singleton approach it would also mean creating some kind of special `ImageBlendParameters` class which would have to be instantiated anyway, defeating the purpose. But it's also possible to increase the number of parameters which can be exposed by including `#include "core/method_bind_ext.gen.inc"` in the source file (if that was one of the reasons behind making an entire class).

Given more methods can be implemented there, makes sense. My rationale is that I wouldn't really want to unnecessarily create classes for each of the processing task (like an `ImageResizer` or so, but maybe this would also make sense to implement actually).

Do you think it would make sense to implement methods like godotengine/godot#23187 in `ImageBlender` class? These methods were actually removed in Godot 3.0 or so...

Is this still work-in-progress?

2020-05-30 16:57 UTC, 98teg commented
Glad you like it! I also considered implementing a method first, but the number of parameters would be too big. I'm not so sure about adding those methods because I would have to read about them carefully first. Right now, the class is fairly flexible and it should be able to do all kinds of blending methods. I think it also is finished, I would like to make it compatible with Godot 4.0 and adding the mask method I told you, but this first method is (hopefully) finished.

2020-05-30 17:14 UTC, Xrayez requested changes
> I would like to make it compatible with Godot 4.0 and adding the mask method I told you

Would make sense to make these changes first before porting then. 🙂

2020-05-30 17:14 UTC, Xrayez commented on classes/image_blender.cpp
> +Color ImageBlender::calculate_factor(Color src, Color dst, BlendFactor factor) {
Godot adds `p_` prefix to parameters, and I try to follow the same convention in the module, but not critical.

Would also benefit making this `const Color &p_src` to improve performance somewhat, and other similar occurrences (except for `enum` and other atomic datatypes).

2020-05-30 17:14 UTC, Xrayez commented on classes/image_blender.cpp
> +	switch (get_rgb_equation()) {
No need to call a method here, just fetched the `rgb_equation` directly.

2020-05-30 17:14 UTC, Xrayez commented on classes/image_blender.cpp
> +	switch (get_alpha_equation()) {
Same as above.

2020-05-30 17:14 UTC, Xrayez commented on classes/image_blender.cpp
> +	ClassDB::bind_method(D_METHOD("get_rgb_dst_factor"), &ImageBlender::get_rgb_dst_factor);
Either duplicate methods or parameters, see error:
```
ERROR: Class ImageBlender already has a method set_rgb_src_factor.
   At: core\class_db.cpp:1232
ERROR: Class ImageBlender already has a method get_rgb_src_factor.
   At: core\class_db.cpp:1232
```

2020-05-30 17:14 UTC, Xrayez commented on classes/image_blender.h
> +    BlendFactor get_alpha_dst_factor(){return alpha_dst_factor;};
Getters can have `const` to ensure compile-time correctness, like:
```c++
BlendEquation get_rgb_equation() const { return rgb_equation; };
```

2020-05-30 17:14 UTC, Xrayez commented on classes/image_blender.h
> +            alpha_dst_factor(FACTOR_ONE_MINUS_SRC_ALPHA){};
Since Godot uses C++11 on the entire codebase, this can be ported to declaration (just assign those values in the `private` section): godotengine/godot#38697.

2020-05-30 17:17 UTC, Xrayez commented on classes/image_blender.cpp
> +	ClassDB::bind_method(D_METHOD("get_rgb_dst_factor"), &ImageBlender::get_rgb_dst_factor);
This is the only thing which needs a fix, other suggestions are not critical for this to be merged.

2020-05-30 17:24 UTC, Xrayez commented on classes/image_blender.cpp
> +
And yeah, would also make sense to add properties for each of the setter/getter pair, like:

```suggestion
ADD_PROPERTY(PropertyInfo(Variant::INT, "rgb_src_factor"), "set_rgb_src_factor", "get_rgb_src_factor");
```

2020-05-30 17:30 UTC, Xrayez commented
Also see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) if you stumble upon problems updating the PR. Ideally you'd just have to `git commit --amend` once you make the changes, and `git push --force origin blending-images`.

2020-05-30 19:32 UTC, 98teg commented
Everything should be fine now! I have one question though, how should I implement the version for Godot 4.0? I might not be able to do it soon because I have to work on other things, but I'm curious about the workflow.

2020-05-30 20:10 UTC, Xrayez approved these changes

2020-05-30 20:14 UTC, Xrayez commented
@98teg it's not required to implement features for both versions, I should probably make this more clear. For now I'll just add this feature as being exclusive for `master-gd4` branch in #3, then either you or me will be able to port this to the next version if needed. Ideally the two branches should remain in sync feature-wise, but I understand that it's not practical to enforce this, I personally I'm not so keen to porting stuff to 4.0 for now due to the same reasons.

If you do port this, you'll just switch to `master-gd4` branch, make PR, change the base branch to `master-gd4` explicitly (as it's not set as default).

2020-05-30 20:15 UTC, Xrayez commented
Thanks for your first contribution!

2020-05-30 20:15 UTC, merged

2020-05-30 22:59 UTC, Xrayez commented
@98teg I've converted the class to inherit Reference in ed39bbd.

I've also generated stub documentation, if you feel like documenting the properties, enums, methods etc: 16c4edf, see [Contribute to the Class Reference](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html).

2020-05-31 08:12 UTC, 98teg commented
Right now I have some other things to work on, but if I have some time to spare later this week I would create some documentation. I'm willing to contribute more to this project in the future!

2020-06-04 15:26 UTC, Xrayez commented
@98teg just letting you know that I've recently deprecated this module (and [some](https://github.com/Xrayez/godot-physicstools) [others](https://github.com/Xrayez/godot-geomtools)) in favor of the new [Goost](https://github.com/GoostGD/goost) module/extension (they are all merged into a single repository now). If you still want to use this module individually, feel free to fork it.

2020-06-04 15:42 UTC, 98teg commented
I'm still interested in participating in the development of this module, but if it is now part of a bigger module I would consider participating in the development of Goost. The only problem that I see is that now there is no sign of my participation in Goost even though it still uses the blender class. This is not much of a problem as far as there is no other mayor change like this in the near future. If that is the case, I would gladly participate in the development of Goost once I finished the things I'm working on.

2020-06-04 16:31 UTC, Xrayez commented
> The only problem that I see is that now there is no sign of my participation in Goost even though it still uses the blender class.

@98teg in fact your name was added to the list of [`AUTHORS.md`](https://github.com/GoostGD/goost/blob/gd3/AUTHORS.md) the moment I created Goost. Unfortunately it's difficult/impossible to merge/retain the history of other `git` projects while creating a new one.

> This is not much of a problem as far as there is no other major change like this in the near future.

Nothing is constant. Always expect things to change, it's open-source community after all.

If you want to formally register yourself as an author within the `git` history, you can update the [CHANGELOG.md](https://github.com/GoostGD/goost/blob/gd3/CHANGELOG.md) file listing the feature you've personally implemented. But given your previous willingness to contribute in the future, that would be probably redundant as you'll end up in the `git` history in any case.

Thanks for understanding, and sorry.

2020-06-04 16:44 UTC, 98teg commented
Ups I didn't see it, my bad! Don't worry, in that case everything is alright :)